### ISSUE TITLE
DTO Generation Failing for Extensions

### ISSUE THREAD

**Issue by pbtura** [stephenh/dtonator#4]
The generation of the DTO classes produces results with invalid syntax for DTOs with inheritance, where the 'properties' config is not explicitly set. If the properties config is missing, the copyOf method of the child DTO will be invalid. If the properties config is set to '*' the constructor of the child class will have duplicate parameters.

example configs from dtonator-features:

**Working**
```
AccountDto:
  domain: Account
  properties: id, name
  tessellModel: true
  forceMapperMethods: name

RedAccountDto:
  extends: AccountDto
  domain: RedAccount
  properties: foo
  tessellModel: true
```

**Invalid 'copyOf'**
```
AccountDto:
  domain: Account
  tessellModel: true
  forceMapperMethods: name

RedAccountDto:
  extends: AccountDto
  domain: RedAccount
  tessellModel: true
```

**Duplicate Constructor Parameters**
```
AccountDto:
  domain: Account
  properties: '*'
  tessellModel: true
  forceMapperMethods: name

RedAccountDto:
  extends: AccountDto
  domain: RedAccount
  properties: '*'
  tessellModel: true
```
